# Online Food Delivery Database Assignment
This notebook generates a dataset, performs normalization, and demonstrates relational algebra concepts.

## Step 1: Generate Sample Dataset

In [5]:
import pandas as pd
df = pd.read_csv('OrderFacts_sample_dataset.csv')
df.head()

,order_id,order_date,customer_id,customer_name,customer_phone,restaurant_id,restaurant_name,item_id,item_name,item_price,quantity,driver_name
0,1,2026-03-6,4,Neha,9090909090,101,Pizza Hub,1003,Veg Burger,120,4,Sanjay
1,2,2026-03-12,5,Arjun,9012345678,103,Spicy Kitchen,1004,Cheese Burger,180,4,Arjun
2,3,2026-03-10,5,Arjun,9012345678,102,Burger Town,1003,Veg Burger,120,4,Sanjay
3,4,2026-03-1,3,Karan,9988776655,101,Pizza Hub,1007,Salad Bowl,140,3,Arjun
4,5,2026-03-4,4,Neha,9090909090,104,Green Bowl,1002,Farmhouse Pizza,350,2,Arjun

## Step 2: First Normal Form (1NF)
Ensure atomic attributes and remove repeating groups.

In [6]:
df_1nf = df.copy()
df_1nf.head()

,order_id,order_date,customer_id,customer_name,customer_phone,restaurant_id,restaurant_name,item_id,item_name,item_price,quantity,driver_name
0,1,2026-03-6,4,Neha,9090909090,101,Pizza Hub,1003,Veg Burger,120,4,Sanjay
1,2,2026-03-12,5,Arjun,9012345678,103,Spicy Kitchen,1004,Cheese Burger,180,4,Arjun
2,3,2026-03-10,5,Arjun,9012345678,102,Burger Town,1003,Veg Burger,120,4,Sanjay
3,4,2026-03-1,3,Karan,9988776655,101,Pizza Hub,1007,Salad Bowl,140,3,Arjun
4,5,2026-03-4,4,Neha,9090909090,104,Green Bowl,1002,Farmhouse Pizza,350,2,Arjun

## Step 3: Second Normal Form (2NF)
Remove partial dependencies from composite key.

In [7]:
customers = df[['customer_id','customer_name','customer_phone']].drop_duplicates()
restaurants = df[['restaurant_id','restaurant_name']].drop_duplicates()
menu_items = df[['item_id','item_name','item_price','restaurant_id']].drop_duplicates()

orders = df[['order_id','order_date','customer_id','restaurant_id','driver_name']]
order_items = df[['order_id','item_id','quantity']]

customers.head()

    customer_id customer_name  customer_phone
0             4          Neha      9090909090
1             5         Arjun      9012345678
3             3         Karan      9988776655
7             1           Avi      9876543210
10            2          Riya      9123456780

## Step 4: Third Normal Form (3NF)
Remove transitive dependencies.

In [8]:
delivery = df[['order_id','driver_name']]
delivery.head()

   order_id driver_name
0         1      Sanjay
1         2       Arjun
2         3      Sanjay
3         4       Arjun
4         5       Arjun

## Step 5: Example Relational Algebra Queries

1. Orders by a specific customer  
σ(customer_id = 1)(Orders)

2. Menu items with price > 200  
σ(price > 200)(MenuItem)

3. Join Orders and Customers  
Orders ⨝ Customers

4. Item names with quantities  
π(item_name, quantity)(MenuItem ⨝ OrderItems)

5. Total quantity per order  
γ(order_id, SUM(quantity))(OrderItems)

## Step 6: Pandas Operations vs Relational Algebra

In [9]:
# Merge (Join)
merged = orders.merge(customers,on='customer_id')
merged.head()

,order_id,order_date,customer_id,restaurant_id,driver_name,customer_name,customer_phone
0,1,2026-03-6,4,101,Sanjay,Neha,9090909090
1,2,2026-03-12,5,103,Arjun,Arjun,9012345678
2,3,2026-03-10,5,102,Sanjay,Arjun,9012345678
3,4,2026-03-1,3,101,Arjun,Karan,9988776655
4,5,2026-03-4,4,104,Arjun,Neha,9090909090

In [10]:
# Groupby + Aggregate
order_totals = order_items.groupby('order_id')['quantity'].sum()
order_totals.head()

order_id
1    4
2    4
3    4
4    3
5    2
Name: quantity, dtype: int64

In [11]:
# Filter (Selection)
expensive_items = menu_items[menu_items['item_price'] > 200]
expensive_items

    item_id         item_name  item_price  restaurant_id
4      1002   Farmhouse Pizza         350            104
5      1002   Farmhouse Pizza         350            102
7      1001  Margherita Pizza         250            101
9      1005    Paneer Biryani         220            103
13     1002   Farmhouse Pizza         350            101
18     1001  Margherita Pizza         250            103
24     1005    Paneer Biryani         220            102
30     1001  Margherita Pizza         250            104
31     1005    Paneer Biryani         220            101
38     1001  Margherita Pizza         250            102